# Generated by Django 4.2.6 on 2023-10-24 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('brand_image', models.ImageField(default=None, null=True, upload_to='brandimg/')),
            ],
        ),
        migrations.CreateModel(
            name='phonemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=200, null=True)),
                ('release_year', models.DateField()),
                ('available_quantities', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_available', models.BooleanField()),
                ('mobile_image', models.ImageField(default=None, null=True, upload_to='mobimg/')),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartphone.brand')),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('tran_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=20, null=True)),
                ('t_amount', models.IntegerField()),
                ('trans_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartphone.phonemodel')),
                ('usersample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
