# Generated by Django 4.0.5 on 2023-11-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0004_rename_transaction_mobile_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_trans',
            name='trans_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='smartphone.phonemodel'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='smartphone.brand'),
        ),
    ]
